### ISSUE TITLE
The polygon hasPoint(x, y) seems to be not working as expected

### ISSUE THREAD

**Issue by vinimdocarmo** [jsxgraph/jsxgraph#149]
In the following code I'm creating a square of side equals 4. Then, I check wheter the point (1, 1) is inside the polygon.
```javascript
var board = JXG.JSXGraph.initBoard('jxgbox', {boundingbox:[-4, 6, 10, -4], axis: true, zoom: {wheel: true}, grid: false, keepaspectratio: true, showcopyright: true});

var p1 = board.create('point', [0.0, 0.0]);
var p2 = board.create('point', [0.0, 4.0]);
var p3 = board.create('point', [4.0, 4.0]);
var p4 = board.create('point', [4.0, 0.0]);

var p = board.create('polygon', [p1, p2, p3, p4]);

console.log(p.hasPoint(1, 1)); // returns false instead of true
```
In this case, the method `hasPoint` returns `false` instead of `true`.

**Comment by alfredwassermann** [comment]
The object polygon has the attribute `hasInnerPoints` which is by default set to `false`. It decides if `hasPoint()` is true on the polygon edges only (in case `hasInnerPoints==false`) or if also the inner points of the polygon area return `true` on `hasPoint()` (in case `hasInnerPoints==true`).
Moreover, `hasPoint()` expects as input coordinates given in pixel.

In summary, your example should work with the following modifications:

    var p = board.create('polygon', [p1, p2, p3, p4], {hasInnerPoints: true});
    var c = new JXG.Coords(JXG.COORDS_BY_USER, [1, 1], board);
    console.log(p.hasPoint(c.scrCoords[1], c.scrCoords[2]));

**Comment by vinimdocarmo** [comment]
Thank you :smiley:

**Comment by mkraska** [comment]
Would this be a good way to make a function based on the proposed solution?

```javascript
function isPointInPoly(pt,po) { 
  let c = new JXG.Coords(JXG.COORDS_BY_USER, [pt.X(), pt.Y()], board);
  return po.hasPoint(c.scrCoords[1], c.scrCoords[2])}
```
Seems to work but is it efficient? [jsfiddle](https://jsfiddle.net/tekzbhx2/)

**Comment by alfredwassermann** [comment]
Thank you very much for pointing this out. I just extended the isOn method to polygons with hasInnerPoints == true.
It will be available in today's nightly build.
Using hasPoint() in your proposed method is no problem in terms of efficiency (the bug fix uses the same internal algorithm), but will return mathematical incorrect results. The reason is that in hasPoint the polygon is enlarged by a slight margin of a few pixel (depending on the input device and the strokeWidth) to allow highlighting even if the pointer device is not exactly above the polygon's edges (this is the main use of hasPoint).

**Comment by mkraska** [comment]
Thank you for clarifying and improving the feature. 

It will take a while until I can use that in STACK (current version uses JSXGraph 1.2.1, which is therefore also the setting of my [MecLib](https://github.com/mkraska/meclib) [tryout jsfiddle](https://jsfiddle.net/yjwa3kzv/2/)

The slight enlargement is not a problem for me, because I use the function for checking visual proximity of objects.

**Comment by mkraska** [comment]
Now I come to a point where I would like to control the tolerance of hasPoint() in my proximity check. Is that possible locally (without affecting interactive highlighting)?

**Comment by alfredwassermann** [comment]
The easiest way of the `hasPoint` method in your own code is the following:

- do not use the precision attribute for individual objects, i.e. stay with the default value `'inherit'`.
- In your method:
    - store the global precision value of the board
    - set the global `precision.hasPoint` value of the board to the value you need
    - call `hasPoint()`
    - restore the global precision value
 - Example:

```
    const board = JXG.JSXGraph.initBoard('jxgbox', { 
         boundingbox: [-5, 5, 5, -5], axis:true
    });
    var A = board.create('circle', [[0, 0], 2], {hasInnerPoints: true});
    var B = board.create('point', [3, 3], {name: 'drag me'});
    var txt = board.create('text', [-3, 3, function() {
	var prec_tmp, is_in;
	
        prec_tmp = board.options.precision.hasPoint;
        board.options.precision.hasPoint = 0;
        is_in = A.hasPoint( B.coords.scrCoords[1], B.coords.scrCoords[2] );
        board.options.precision.hasPoint = prec_tmp;
        return (is_in) ? 'B is inside' : 'B is outside';
    }]);
```
See it at https://jsfiddle.net/qer71u9t/1/

**Comment by mkraska** [comment]
Thanks a lot. After playing a bit around with your jsfiddle example, I see that such a proximity check is dependent on the strokeWidth of the target element (circle in this case). 

I also plan to perform experiments with attractor lists, attractor distance and snatchdistance in order to facilitate unambiguous positioning of points on other objects.
