### ISSUE TITLE
Wrong calculating of touch events when zooming in on Android

### ISSUE THREAD

**Issue by karoltarasiuk** [jsxgraph/jsxgraph#190]
To replicate the issue follow this steps:
1. Take some Android device and Chrome browser
2. Go to this page: http://jsxgraph.uni-bayreuth.de/wiki/index.php/Polygon_II
3. Ensure that the view is completely zoomed out
4. Try to move point B around - works perfectly
5. Now pinch and zoom in
6. Try to move point B around - you can't, as you can't really grab the point

There is something wrong with calculating the coordinates on Android. It works well in iOS.

**Comment by karoltarasiuk** [comment]
@alfredwassermann I don't know whether I should close this issue, as the newest `getOffset` method from `src/utils/env.js` fixes the problem within our product. Unfortunately it still doesn't work for your [Polygon ||](http://jsxgraph.uni-bayreuth.de/wiki/index.php/Polygon_II) example. You load JSXGraph 0.99.4 and this version contains the newest version of this method.

The compare link is here: https://github.com/karoltarasiuk/jsxgraph/compare/v0.99.4...master But I wasn't really going thoroughly through it to see what's causing the problem.

I noticed though by comparing those two:
https://github.com/karoltarasiuk/jsxgraph/commits/v0.99.4/src/utils/env.js and
https://github.com/karoltarasiuk/jsxgraph/commits/master/src/utils/env.js
that the only meaningful commit changing `src/utils/env.js` file is this:
https://github.com/karoltarasiuk/jsxgraph/commit/99d8d1a7542dd8457efb13193d1f4905cf7ce315#diff-eac6f78170256c598e70ce4b121d69ca

Maybe just try to replace a version you're loading to the newest one?

**Comment by karoltarasiuk** [comment]
Ah - and sorry - all the links are from my fork, but it's exactly the same as yours so didn't bother changing...

**Comment by alfredwassermann** [comment]
This problem was hard to fix. But now there seems to be a solution. The problem is that Chrome on Android distinguishes two types of scrolling:

a) If `<meta name="viewport" content="user-scalable=yes">` scrolling means the visual viewport is changed. The values of scrollLeft and scrollTop contain the scroll distance, but                  getBoundingClientRect() is unchanged. To get the correct position, the scrolling has to be ignored.
b) In case `<meta name="viewport" content="user-scalable=no">` scrolling is like scrolling on a desktop computer. 

I hope that all browser/OS combinations are covered by the fix.
