### ISSUE TITLE
Dependencies required to build on Ubuntu

### ISSUE THREAD

**Issue by christianp** [jsxgraph/jsxgraph#225]
I had to install a few dependencies on my Ubuntu 14.04 machine before I could install the npm dependencies. It's not easy to work out from the npm log what you need to do, so I think it should be documented somewhere.

First I ran 

```
sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++ 
```

to install the cairo development files, and then I also had to install `nodejs-legacy` because node-gyp tried to call `node`, while the binary has been renamed to `nodejs` on Debian.

Weirdly, I had to install `zip` to build the various .zip files. I assumed this was preinstalled on Ubuntu - is my environment weird?

**Comment by migerh** [comment]
This is due to the optional dependency to canvas. The dependencies for various systems are mentioned there: https://www.npmjs.com/package/canvas. This is only required if you want to render JSXGraph constructions from node into png.

But you're right, there should at least be some note about this being optional and a link to the canvas readme.

**Comment by nikolas** [comment]
Even though it's listed as an optional dependency, installing `jsxgraph` tries to build `canvas` on my system. That fails with this error:

```
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamJPEGSync(Nan::NAN_METHOD_ARGS_TYPE)’:                                                              
../src/Canvas.cc:458:12: error: no matching function for call to ‘v8::TryCatch::TryCatch()’                                                                                                     
   TryCatch try_catch;  
```

This problem is possibly fixed upstream. canvas 1.3.16 is a really old version of this library - from May 29, 2016. Is there any way we can update jsxgraph's dependency to canvas 1.6.x?

**Comment by migerh** [comment]
Canvas was updated to 1.6.x with #273.

**Comment by alfredwassermann** [comment]
Since 43ba031c920faffb916c7d6724f63f98f3229c4c dependencies should be ok - for now.
