### ISSUE TITLE
Odd behavior with resizeContainer and keepAspectRatio

### ISSUE THREAD

**Issue by RDerber** [jsxgraph/jsxgraph#269]
http://jsfiddle.net/4jqrcuw1/27/

It seems that keepAspectRatio isn't being applied when a graph is resized to be larger than it was, but it is applied when a graph is made smaller. This results in compacting graph elements when repeatedly shrinking and growing a graph with this attribute set. The given fiddle demonstrates this behavior.

**Comment by alfredwassermann** [comment]
Yes, indeed this is an odd behavior, but it can be explained:  When calling `resizeContainer()`, the actual bounding box is read, then the new width and height of the container is set and finally the new bounding box is set so that the aspect ratio is kept.. After having resized the container to the smaller width the board does not know that initial value of the bounding box and it is safer to set it to the smaller value.

Another approach for your problem could be to set the css width and height of the div and then call setBoundingBox with your preferred values:

    var div = document.createElement("div")
    document.body.appendChild(div)
    div.style.width = "300px";
    div.style.height = "300px";
    var id = "jxgbox"
    div.id = id
    var board = JXG.JSXGraph.initBoard(id, {
      boundingbox: [-5, 5, 5, -5],
      keepAspectRatio: true,
    })
    board.create('point', [0, 0])
    board.create('point', [1, 1])
    board.create('point', [1, 2])
    board.create('point', [2, 2])
    board.create('point', [3, 3])

    var i = 0;
    setInterval(() => {
      if (i % 2) {
      	div.style.width = "200px";
      } else {
    	div.style.width = "300px";  
      }
      board.setBoundingBox([-5, 5, 5, -5], true);
      i = i + 1
    }, 500)

See http://jsfiddle.net/4jqrcuw1/37/
Best wishes,
Alfred
