### ISSUE TITLE
How can i to learn jsxgraph source code

### ISSUE THREAD

**Issue by ghost** [jsxgraph/jsxgraph#296]
I am sorry to ask this question in place. 
I am a beginner of jsxgraph. I want to learn the source code of jsxgraph. because I have a similar project, but I am not allowed to use this library. Can you tell me how to learn this source code ? 

Thank you~

**Comment by alfredwassermann** [comment]
What exactly do you want to know? How to generate graphics in the browser or how to do geometry?

**Comment by BassilRedman** [comment]
Hi
I am not the OP, but am also interested in the code. I would like to have an understanding of the general structure of the code: What are the main objects and how does the rendering process work?
Thanks for making JSXGraph!
Best

**Comment by alfredwassermann** [comment]
Obviously, it would take a long time to explain everything. Here are some key points:

* All geometric objects are derived from GeometryElement in `base/element.js`
* All calculations are done with Coords objects. The Coords object has "user coordinates" (usrCoord) which refer to the visible axes units and "screen coordinates" (`scrCoords`) having pixels as units. 
* JSXGraph uses *homogeneous coordinates* (where the first coordinates is always the `z`-coordinate). This is convenient, since many special cases are avoided. For example, if the `z`-coordinate is 1, the point is finite and the second and third entries are the usual `x`- and `y`-coordinates. If `z==0`, the the point is infinite.
* The mathematics (intersections, plotting, ...) is done in the geometric objects or in methods in the folder `math`.
* Every "move" or "up" event triggers an update of (most) elements (board.update): First the `Coords`-objects of all elements are updated. After having this done for all objects, all objects are updated by the renderer.
* Possible renderers are SVG (default), canvas, vml (ancient IEs), and "no".  
The latter is useful if one wants to run JSXGraph on serverside.
* The event handling (including multi-touch) is done in `base/board.js`. Since iOS 13, all major browsers use pointer events.  For backwards compatibility, JSXGraph also supports touch events (Apple) and mouse events.
* Highlighting is also controlled by JSXGraph: every element has a method `hasPoint(x, y)`, which decides if the pointing device is close enough to the element. 
* The visual appearance is controlled by "attributes". The default attributes are set in `options.js`. 
* Most construction values and attribute values can be either constant values or functions.
The latter enables the dynamic behaviour and modelling of dependencies  between objects.
* As a parallel project we have a language called *JessieCode*, https://github.com/jsxgraph/JessieCode, which is able to parse mathematical expressions (and more). This allows the user to supply something like `board.create('functiongrpah', ["sin(x)"])` instead of using `Math.sin(x)`.

Please, ask if you have more specific questions.

Do you mind if I close this issue? I would propose to continue the discussion on Google groups: https://groups.google.com/forum/#!forum/jsxgraph

Best wishes,
Alfred

**Comment by BassilRedman** [comment]
Hello,

Thank you! This is very helpful. I will post future questions on Google groups.

Best
