### ISSUE TITLE
npm package update

### ISSUE THREAD

**Issue by azaloga** [jsxgraph/jsxgraph#298]
Any chance that the npm package can be updated to match the one on github? The canvas dependency version is still 1.3.x there and is causing a bit of a pain with compilation, whereas the latest ^2.0.0 works just fine.

And a big thank you for the wonderful library!

**Comment by Sjiep** [comment]
I have the same problem as @azaloga after adding the package dependency it throws an error during the install of canvas (which is marked as dependency).

```
> canvas@1.3.16 install .../node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
```
Hopefully this would then also fix the error I get from webpack when trying to `import JXG from 'jsxgraph'`
```
Module not found: Error: Can't resolve 'canvas' in '.../node_modules/jsxgraph/distrib'
```

**Comment by Sjiep** [comment]
@alfredwassermann is there any progress on this?

I'm trying to switch from adding jsxgraph in the HTML head section to importing it as a JS module. The version on npm fails during `npm install` because of the canvas 1.3.x optional dependency. My current solution is to use the master branch from github as package dependency and then run `make core-min` from there.

**Comment by alfredwassermann** [comment]
Should be done with v1.00.0
