### ISSUE TITLE
Copyright message displays version 0.99.6?

### ISSUE THREAD

**Issue by axkr** [jsxgraph/jsxgraph#304]
We are using version 1.3.5 from CDN but the copyright message displays 0.99.6 ?

- https://cdnjs.cloudflare.com/ajax/libs/jsxgraph/1.3.5/jsxgraphcore.js

**Comment by migerh** [comment]
I think that was by accident. There is no JSXGraph version 1.3.5. but there is a tag named 'v1.3.5' and there is [a bot](https://github.com/PeterBot) that used this tag to publish version v1.3.5 to the [cdnjs](https://github.com/cdnjs/cdnjs) repository in [this commit](https://github.com/cdnjs/cdnjs/commit/16d48abb2f0653dd4c0d20a3a656404287659e9a). So what you are actually using is some intermediate version between 0.99.6 and 0.99.7. That's why it says 0.99.6 in the copyright.

**Comment by migerh** [comment]
@alfredwassermann This is actually really bad. On cdnjs.com people are offered 1.3.5 although 0.99.7 technically is a newer version. There should be no tags that look like vx.y.z except JSXGraph releases. If you need tags to pin a certain version for e.g. sketchometry you should name it differently. If you want to get the 1.3.5 version removed from the cdnjs repo: watch out, that repo is over 150GB.

**Comment by axkr** [comment]
Ok we are now using JSXGraph 0.99.7 for our Android Beta:
- https://github.com/axkr/symja_android_library/wiki/BETA-tests

The evaluation of math expressions is done with this library:
- https://github.com/paulmasson/math

With the JSForm function you can generate the JavaScript form which is used internally:

![jsxgraph_usage](https://user-images.githubusercontent.com/3109793/68230942-600ecb80-fffa-11e9-92ea-750bc9c03b7b.png)
