### ISSUE TITLE
Arrow head extends past the end of a line

### ISSUE THREAD

**Issue by christianp** [jsxgraph/jsxgraph#322]
I think this is the same problem as #317, but that's closed and the problem still occurs in JSXGraph 1.1.

The arrow head on the end of a line is drawn with its centre on the end of the line, instead of the tip.
I've got a minimal example at https://codepen.io/christianp/pen/MWygRjY

![image](https://user-images.githubusercontent.com/19513/89288922-516b4880-d64e-11ea-9887-fed5895c012b.png)

@alfredwassermann claimed in the thread linked in #317 that this was fixed - is that in a version that hasn't been released yet?

**Comment by alfredwassermann** [comment]
This has been fixed in a previous version for lines. But there is a regression which is meanwhile fixed in the development version.
The regression is: in v1.1.0 the arrow head ends at the specified position if specified with a size attribute like

    lastArrow: {type: 1, size: 6, highlightSize: 8}

The positioning fails in v1.1.0 if specified as

    lastArrow: true

In the last nightly builds both versions should work.

**Comment by christianp** [comment]
Thanks!

**Comment by YannickNeyt** [comment]
Is this broken again?
https://jsfiddle.net/9t2n3ds7/
