### ISSUE TITLE
Layer order not respected if layer is 20 or higher

### ISSUE THREAD

**Issue by dgca** [jsxgraph/jsxgraph#337]
Hi all, I noticed that if you create an element with a layer higher than 20, elements with a lower layer may be drawn on top. This is not expected behavior since a higher layer should mean an element is above one with a lower layer.

I put together [this example](https://codesandbox.io/s/jsxgraph-layers-issue-56ykc?file=/src/index.js) to demonstrate.

I'm creating two pairs of intersecting lines: AB/CD and EF/GH

Lines AB/CD are behaving as expected. Though line AB was created _before_ CD (and would therefore be underneath by default), I gave a higher layer of 19—as opposed to line CD's layer of 18.

The issue appears in lines EF/GH. Line EF has a layer of 20, which is higher than line GH's layer of 19. Despite this, line EF appears _underneath_ line GH.

**Comment by alfredwassermann** [comment]
The example shows the expected behavior: there are 20 layers numbered from 0 to 19. Since there is no layer 20, line EF is in layer 19. Since EF is constructed before GH, EF is underneath GH.

If you really need it, you can increase the number of layers by setting e.g. 

    JXG.Options.layer.numlayers = 21;

**before** calling `initBoard`.
