### ISSUE TITLE
firstArrow and lastArrow no longer work with a 'curve' for version 1.2.1

### ISSUE THREAD

**Issue by drgrice1** [jsxgraph/jsxgraph#343]
A minimal example where this happens is:
```javascript
var board = JXG.JSXGraph.initBoard('box', { boundingbox: [-8, 8, 8, -8], });
board.create('curve', [ function(t) { return t; }, function(t) { return Math.sqrt(t); }, 0, 7 ], { lastArrow: true });
```
The console shows errors, and no curve appears.

This worked for previous versions.

**Comment by drgrice1** [comment]
I discovered that firstArrow and lastArrow do work if set after curve creation, instead of being passed to the options.
For example:
```javascript
var board = JXG.JSXGraph.initBoard('box', { boundingbox: [-8, 8, 8, -8], });
var curve = board.create('curve', [ function(t) { return t; }, function(t) { return Math.sqrt(t); }, 0, 7 ]);
curve.setArrow(false, true);
```

**Comment by drgrice1** [comment]
Further testing shows that you can set the firstArrow and lastArrow in the options when the curve is first set, but you must do both.  If only one is set, the error occurs.  Prior versions allowed setting only one, and presumably defaulted to false for the other.

**Comment by alfredwassermann** [comment]
Thanks a lot for pointing out this bug. Incidentally, it had already been post a few days a ago in google groups: https://groups.google.com/g/jsxgraph/c/OG5cQJr6W8o. 
Meanwhile, the bug is fixed in the sources. As you already wrote, a workaround until the next version is released is to set:

    JXG.Options.curve.firstArrow = false;
    JXG.Options.curve.lastArrow = false;

after loading JSXGraph and before creating a board.
Best wishes and again many thanks,
Alfred

**Comment by drgrice1** [comment]
Ahh, I didn't check google groups.
