### ISSUE TITLE
dash not working when having arrowheads

### ISSUE THREAD

**Issue by appeye** [jsxgraph/jsxgraph#355]
The dash options does not seem to work on curves when arrow heads are also enabled. (v.1.2.2)

maybe related to this issue
https://github.com/jsxgraph/jsxgraph/issues/344

**Comment by appeye** [comment]
does work in 1.00.0

**Comment by alfredwassermann** [comment]
The combination of dashes and arrow heads on curves is not working properly yet. At the moment I have no solution which is completely satisfying.

**Comment by appeye** [comment]
Ok! thank you for the reply

**Comment by alfredwassermann** [comment]
Nevertheless, there might be a solution: we have to create special arrow head which can end exactly at the end of the curve path.

The existing arrow heads are shifted slightly forward so that the end of the straight line path is covered completely by the arrow head. Then, the line has to be shortened by this shift. This is an nearly impossible task to do for non-straight lines.

It will take a while, but we are working on it.

**Comment by alfredwassermann** [comment]
It is interesting to see that others are struggling with the same problem. In the source code of v1.2.4, I've added the new arrow head `type:7`. It consists of two curved lines which end in the same direction as the curve or line and their thickness is the same as that of the curve. Thus, their is no "tooth" at the tip of the line and there is no need to shorten the curve line. Further, also curves now support the attribute `lineCap` and with `lineCap: 'butt'` the curve arrow ends exactly at the desired position.
`type:7` is the new default value for curves. Other arrow types might follow...

![screendump](https://user-images.githubusercontent.com/986107/127295289-a53eff54-3593-41a0-a337-c5a7fd135b84.png)

**Comment by appeye** [comment]
ah great! thank you for addressing this
