### ISSUE TITLE
Support for ES6 module (with Typescript)

### ISSUE THREAD

**Issue by weissleon** [jsxgraph/jsxgraph#400]
Hi, I am trying to use JSXGraph on React project.

I am currently using Typescript, and when I attempt to import the `jsxgraph` package installed through `npm`, 
it warns me that `"node_modules/jsxgraph/distrib/index.d.ts' is not a module."`

Also, even after updating to `1.4.0`, the compiler is still complaining `"Module not found: Can't resolve 'canvas'`.
If I remember correctly, the canvas issue should have been resolved in `1.4.0`.

Any suggestions on how to get around these 2 issues?

**JSXGraph Version**: 1.4.0
**React Version**: 17.0.2

**Comment by alfredwassermann** [comment]
Hi, 
thank you very much for pointing out the `'index.d.ts' is not a module` problem. We will try to address this very soon.

Regarding the canvas issue: No, the fix is not in 1.4.0, but will be in 1.4.1 (or you can try a recent nightly build).
1.4.1 will be released as soon as `'index.d.ts' is not a module` problem is fixed..

**Comment by alfredwassermann** [comment]
Just fixed some problems in index.d.ts. In today's nightly build, the following TypeScript code

    import 'jsxgraph';
    const board = JXG.JSXGraph.initBoard('test');

will compile.
