### ISSUE TITLE
According to Lighthouse, jsxgraph does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by holgerengels** [jsxgraph/jsxgraph#497]
That should be quite simple to fix ..

[Lighthouse - Use passive listeners to improve scrolling performance](https://developer.chrome.com/docs/lighthouse/best-practices/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools)

**Comment by alfredwassermann** [comment]
Unfortunately not: Lighthouse complains about the generic method `JXG.addEvent` which calls `addEventListener`.  I updated this method to hand over a third parameter `options`, but Lighthouse still complains. 

In fact, I consider the complaint as meaningless, since the property `passive:true` only affects touch and wheel events and in JSXGraph these events call `preventDefault`, i.e. `passive:true` will not help anyway.
