### ISSUE TITLE
highlighting of polygons

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#562]
For polygons with hasInnerPoints: true, the borders are only highlighted by opacity. For example, if the highlightStrokeWidth is adjusted, this is not taken into account (only when you hover over the border itself).

https://jsfiddle.net/6hpmdef2/

In addition, as soon as the highlightStrokeColor is set, the highlightStrokeOpacity appears to be set to 1.

**Comment by alfredwassermann** [comment]
So far, this was intentional. Otherwise, it is not possible for the user to distinguish the highlighting of a single border and of the whole polygon in the cases where the polygon is not filled. Polygons without fill color are quite common in the context of Euclidean geometry.

But if more people vote to change this behaviour, we could also change the `strokeWidth` of the borders on highlighting.

Can you please create a jsfiddle for the second problem?

**Comment by alfredwassermann** [comment]
Fixed by a19e25af4942f41c3051acb066f948426b441244
