### ISSUE TITLE
Differences in received data and plotted data

### ISSUE THREAD

**Issue by wesselvl1** [jsxgraph/jsxgraph#608]
I am working on an application where data precision is key. But also where modification and moving of certain points is key.

While I have been working on this for a while now. I started noticing some incosistensies I could not seem to be able to figure out.

I am a API written in Python which handles a lot of the calculations, where JSXGraph acts as a way where the user can visualize and manipulate points where Python recalculates values based on these changes. I also have some sort of auto fit where these points can be set to a "best fit".

For one of these points (glider) I am determining it's best fit location in Python resulting in the following x, y values followed by the values console.log(glider.X()) and it's Y counterpart.

| | Python Values | JSXGraph Values |
|--------|--------|--------|
| X | 0.09337136731079021 | 0.09337040094117298 |
| Y | 0.006033141689030274 | 0.006048763347103392 |

As you can imagine, when precision is key. This "slight" difference in data makes it so this application cannot be used. And I was wondering where this might, or does come from so I can explain it to my supervisor and the validators.

If there is a fix aswell I would be glad to know.

Not sure if I should provide any code? Since it is mostly based on the prinicipal of there being difference in data used to create the point and the actual value of that point in the graph.

**Comment by alfredwassermann** [comment]
If I understand correct, you set a glider e.g. to the Python coordinates (0.09337136731079021, 0.006033141689030274) and then the *glider* positions "itself" to (0.09337040094117298, 0.006048763347103392).

JSXGraph projects *glider* elements to their parent element, where the projection algorithm depends on the parent element's type. If the parent element is a curve or function graph given by some expression (which I assume in your case), then the projection is done by a root finding algorithm (JSXGraph uses Brent's zero finder). The precision of the root finder is mostly determined by the constant JXG.Math.eps which has default value 0.000001. Incidentally, this is exactly the magnitude of the difference between the numbers from Python and JSXGraph.

As a first test, you can set  JXG.Math.eps to some smaller value before calling initBoard. However, this is dangerous, since this tolerance is used in many places and a change might break JSXGraph elsewhere.
However, if your results are promising, we can think about introducing a separate, user-controllable tolerance for the root finder.

**Comment by alfredwassermann** [comment]
Do I understand correct?

- You have a function $f$. If you evaluate $f$ for a certain value of $x$, e.g. $x_0=0.09337040094117298$, then the functions value $f(x_0)$ computed by Python and JSXGraph are the same up to 16 digits.

- If you position a glider to the coordinates $x_0, f(x_0)$, then the glider's position is slightly off, e.g. to $x=0.09337127668997432$. 

What do you mean exactly with: "I already got the correct Y value from both my Python Data as the Plot Data."?
How does the function $f$ look at $x_0=0.09337040094117298$? Is it flat?

Would it be possible, to post an example function?

**Comment by wesselvl1** [comment]
It's not a function, but a curve based on a list of X and Y values read from a machine applying a load. But in a best case scenario this curve would ressemble an S when place in a logarithmic time scale. I'll show the graph in question below. Where the red dot (a) is the one in question right now.

![image](https://github.com/jsxgraph/jsxgraph/assets/113102091/28f9589f-5c0c-4433-95b8-215fa8a380c4)

When determinating the X and Y values of that given point, called a (or t1). I am using numpy's np.interp and np.full_like to determine the intersection between the curve and (straight line vertical line since X is a given, just need Y).

Those values I am storing in a Point variable consisting of X, Y (and Id). After receiving these values from python I am repositioning the intersection and recreating point a as following

`let a = this.board.create('glider', [this.casagrande.casagrande0.x, this.casagrande.casagrande0.y, this.curve], {
      name: '\\[a\\]',
      size: 3,
      strokeColor: 'red',
      fillColor: 'red',
      visible: true,
      withLabel: true,
      label: {
        fontSize: 15
      }
    });`
    
    Where casagrande0 is point a in question. But neither X and Y would align with the values received from Python.

**Comment by alfredwassermann** [comment]
Aha, so `this.curve` is given by two arrays containing the log values of `[log(X_1), ....], [log(Y_1),...]` containing all the data points read from that machine?

**Comment by alfredwassermann** [comment]
One more question: do you apply the Python methods to the values X, Y or to their log values?

**Comment by alfredwassermann** [comment]
I guess, the reason for the discrepancy is the following: in the python version, the coordinates of the point on the curve is determined with `np.interp` as the vertical projection of a point $A$ to the curve, where the curve consists of linear segments. Let's have a very simple example consisting of a single segment:

```
x = np.array([0, 4])
y = np.array([0, 2])
np.interp(2, x, y);
# Output: 1.0
```

That is, a glider with initial values $(2, 2)$ would be  positioned to $(2, 1)$.

JSXGraph uses orthogonal projection instead of vertical projection. With the same data, the glider would be positioned to $(2.4, 1.2)$:
![screenshot](https://github.com/jsxgraph/jsxgraph/assets/986107/5cded6b9-94e9-462d-b69a-233b9fd4d8cd)

In the picture, $C$ is the python point, $B$ is the JSXGraph point (see it live at https://jsfiddle.net/jbwkpgLa/1/). $B$ is the closest point to $A$ on the curve, but of course $C$ is easier to determine. 

In order to align the values with the python output, you therefore should first create the vertical projection and from this  the glider: Here `p` is the data point you want to project.

```
var  = board.create('point', [X, Y]], {visible: false});
var li2 = board.create('line', [p, [()=>p.X(), 0]], {strokeWidth: 0.5, dash:3});
var C = board.create('intersection', [li2, curve], {name: 'C', label: {offset: [-10, 10]}});
var D = board.create('glider', [C.X(), C.Y(), curve], {name: 'a', color: 'black', label: {offset: [-10, -10]}});
```

**Comment by wesselvl1** [comment]
Aha yes, I see. And it does kind of make sense now.

I will see what I can do with this. Thank you very much.

**Comment by wesselvl1** [comment]
> One more question: do you apply the Python methods to the values X, Y or to their log values?

Also, I was using the Log Value from the X value
