### ISSUE TITLE
Every dblclick is also a click 

### ISSUE THREAD

**Issue by Mat-Ge** [jsxgraph/jsxgraph#645]
Currently, it does not seem to be possible to double-click an object without clicking the object directly in front of it.

**Comment by alfredwassermann** [comment]
Sorry, I do not quite understand. What do you mean with "in front of it". Can you please provide a minimal example?

At the time being (v1.8.0), any dblclick event is accompanied by two click events. We try to fix that.

**Comment by christianp** [comment]
I think "in front of it" should have been "before it".

The normal DOM also fires two `click` events before a `dblclick` event (see [this demonstration](https://click-dblclick.think.somethingorotherwhatever.com/)). I don't think that JSXGraph should differ from that.

**Comment by Mat-Ge** [comment]
I actually meant to write “before”, sorry for that.
Thanks for the link Christian. I wasn't aware of that. That's inconvenient for what I had in mind, but of course JSXGraph should not differ from the normal DOM here.
Likewise, I would like to be able to move objects without triggering a click event, but that would probably also differ from the usual DOM.
I tried to illustrate the problem with this [JSFiddel](https://jsfiddle.net/geissbuehlerm/hqLkesbt/24/), but apparently I need to implement my idea differently.

**Comment by alfredwassermann** [comment]
I just fixed this problem in the develop branch. Now, a double click event suppresses any click event. The drawback is that there is now a new board attribute `clickDelay` which specifies the time interval after which the waiting for a double click is abandoned.
However, as outlined in https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event, JavaScript itself fires even two click events in addition to a double click (probably because of this device dependent delay). Actually, I find this annoying, because it delegates the work to distinguish between click and double click to the developer.

Any opinions on this?

**Comment by christianp** [comment]
I don't think that cancelling the `click` events is a good idea. I'd rather write the `dblclick` handler on the understanding that there must have been two `click` events immediately preceding it, and undo whatever effect they had if necessary.

Adding a delay will make the interface less responsive, and won't work for people who have increased the double-click time, usually for accessibility reasons.

**Comment by alfredwassermann** [comment]
What about an option with the default to be the JavaScript default?

**Comment by christianp** [comment]
Sure.

**Comment by alfredwassermann** [comment]
OK, done.  There is the new attribute `dblClickSuppressClick`. By default it is false and every dblclick is preceded by two clicks. Otherwise, the click events are suppressed.

**Comment by Mat-Ge** [comment]
Sounds like a perfect solution to me. Thank you very much.
