### ISSUE TITLE
Board origin is not centered on the element

### ISSUE THREAD

**Issue by rwmorton** [jsxgraph/jsxgraph#659]
I can't seem to figure out why the board origin is not centered on the element. See attached screen capture.

[Screencast from 16-05-2024 10:14:34.webm](https://github.com/jsxgraph/jsxgraph/assets/95928533/36189f8a-5688-49c2-82d6-bb4d2c8e6683)

We are using Tailwind CSS and this is a direct translation of the classes: https://jsfiddle.net/f3j5oy7h/

No issues in the fiddle, not sure how this would be happening?

**Comment by alfredwassermann** [comment]
Would it be possible to supply a screenshot of the problem which shows the whole browser window?

**Comment by rwmorton** [comment]
Thank you Alfred, does this help? As it's an experimental feature we are developing I've had to censor some of the UI.

![image](https://github.com/jsxgraph/jsxgraph/assets/95928533/1638f2fb-6290-4e35-b587-1856a31bb6a7)

**Comment by alfredwassermann** [comment]
Thank you very much. Regarding privacy: It is sufficient to show the gray square with a small margin.

Sorry, I still do not get the problem. Is it like the following?

- The gray square is the div which contains the JSXGraph-div, i.e. column 2 in the jsfiddle.
- Now, either:
  - the JSXGraph div (i.e.  `<div id="jxgbox" class="jxgbox" style="width:500px; height:500px">` ) is displayed to be twice as large as intended (because of some issues with flex or by some scaling by tailwind css), or
  - the JSXGraph board assumes that width and height of its hosting div is twice as large as it should be.

Some hints for debugging:

- Add a border around the JSXGraph div, like `<div id="jxgbox" class="jxgbox" style="width:500px; height:500px; border: 1px black solid;">` 
- At the end of the JSXGraph code, write `board.canvasWidth` and  `board.canvasHeight` to the console and check if both values equal 500.

Best wishes,
Alfred

**Comment by rwmorton** [comment]
Thank you Alfred, turns out it was some weird update issue with a Vue computed ref - took a while to track it down. Sorry for taking up your time, was looking in the wrong place the whole time!
