### ISSUE TITLE
Tangent to circle or curve

### ISSUE THREAD

**Issue by andreas-web** [jsxgraph/jsxgraph#675]
How about the following new function? Draw a tangent to a circle through a slider and another point.

![image](https://github.com/jsxgraph/jsxgraph/assets/30598361/2e237d55-3e8c-4a8e-a541-5501427981ac)

**Comment by andreas-web** [comment]
In addition, it would be nice if a tangent could be drawn in an intersection with an circle (or curve)

![image](https://github.com/jsxgraph/jsxgraph/assets/30598361/0d928bcf-6628-461f-ac28-51b207f822b1)

**Comment by alfredwassermann** [comment]
The first suggestion seems to be unsolvable in general, can you give more details?

For the second suggestion there exists already a solution: The tangent through the point `A` is determined by the [pole point](https://jsxgraph.org/docs/symbols/PolePoint.html) of the circle and the line.

**Comment by gwhitney** [comment]
I obviously can't speak for the original poster, but only speculate that there may be a concern that the construction parameter for the `board.create('tangent', ...)` operation is constrained to be one glider on a curve. One often wants to construct a tangent to a circle through a given external point, or construct a tangent to a circle at some point known to be located on the circle for reasons other than it being a glider on that circle. While I agree that taking the pole of a line with respect to a given circle solves the problem for a point that happens to be the intersection of that circle and that line, there are numerous ways that a point could end up to be (for certain) lying on a given circle -- the circle-point intersection is just one of them.

And while I agree that there are sufficient operations available to construct a tangent to a circle $c$ from an exterior point $B$ (find the center $C$ of $c$, calculate the distance from $B$ to $C$, compute the length $t$ of the tangent segment from $B$ to $c$ using the Pythagorean theorem, and then intersect $c$ with the circle of radius $t$ about $B$), this seems like a fundamental enough operation that JSXGraph might be expected to provide a "canned" way to do it, and I think the natural place someone trying to do it would look is the Tangent creation method.

Finally, I can only speculate that the idea of a "a tangent to a circle through a [g]lider and another point" in the original post was that if c was a circle and B was an external point and A was a glider on c, then constructing a tangent to c from B to A would then force the glider A to glide to the (nearest?) point where a tangent from B could touch c. Not having a full architectural view of JSXGraph at the moment, I am not sure whether such additional constraints on where a glider could lie, beyond its original constraints set at creation time, would fit well with that architecture.

But in any case, at my current level of experience with JSXGraph, I can definitely see that additional methods of drawing tangents, at least to circles, could be desirable. They are not actually needed for the Joyce Euclid project, as Euclid III.17 provides an even simpler method of constructing a tangent from an external point to a circle than the one I suggested above (hard to beat Euclid at his own game!) and then III.17 is only used twice in the entire rest of the work. On the other hand, GeoGebra does provide such an operation (not that GeoGebra is the gold standard of dynamic geometry).

**Comment by andreas-web** [comment]
Dear @gwhitney, thank you for your thoughts on my suggestion. @alfredwassermann and I had already agreed bilaterally (we are on the same campus, but in different buildings). That's why I unfortunately forgot to write again for the community here. My apologies!
But you have also summarized my concerns very well and that is exactly the area of tension in which we operate. 
As far as I know, Alfred has already implemented something and thought about it. I'm sure he'll get back to us in the next few days (at the latest when the next version is released) with the new features or at least some suggestions.

**Comment by alfredwassermann** [comment]
Dear all,
since there are now two votes for enabling the *tangent construction on conics/circles from an external point*, we should do it. The plan is to have it in v1.10.0.

In the last two days, the tangent element has been slightly refactored in the `develop` branch. If you want to test it, use commit 9b808eb5487df67a545030661ac418ea9664cfe0 onward.

Now, the following construction are possible:

1. `board.create('tangent', [glider]);`
2. `board.create('tangent', [point, obj]);`, where `obj` is a line, circle, conic, curve, or function graph.

In 2., `point` can be an arbitrary point on `obj`, that is: glider, defining point, intersection point, ...  Actually, beside for curves, 2. was available since many years, but not documented. What happens if in 2., `point` is not on `obj`? For the last 15 years (at least for most cases) the constructed line had the following properties:

- conic/circle: polar line
- function graph: tangent through vertical projection of `point` to `obj`
- curve/line: tangent through orthogonal projection of `point` to `obj` (this is new)

In the case circle/conic, this behavior seems to be the most natural one (seen from analytic geometry), since the tangent and polar line are the result of the same matrix / vector multiplication.
Further, I hesitate to skip backward compatibility and define `board.create('tangent', [point, obj]);` for an external point to be the tangent to the object, because for conics/circles, the result are two tangents. So, we have to supply a number (0/1) which tangent we want and have one more element 'othertangent', similar to intersection points. I would rather have this functionality in a new element like

`board.create('somename', [point, obj, number]);`, where `obj` is a circle or conic and 
`board.create('othersomename', [point, obj, line]);`, where `obj` is a circle or conic.

What is your opinion? Do you have suggestions for the name?

Best wishes,
Alfred

**Comment by gwhitney** [comment]
I think you are suggesting something like
```
board.create('tangentTo', [point, conic, selector])
```
for the tangent from an external point to a conic, with selector being the additional information needed to choose one of the possible tangents? (I guess there is a canonical ordering between the tangents in that the angle between the two tangents at the point is less than τ/2 so it makes sense to say that one possible tangent point is counterclockwise from the other, from the perspective of the point. Not sure if there are other more salient ways to pick which tangent.) Or I suppose you could drop selector and get back an array of two elements... 

And then I guess the idea of the other function is that if line is one tangent from the point to the conic, then it constructs the other tangent from the point to the conic? I guess then if you were to use the `tangentTo` name I suggested, it would be reasonable to call that `otherTangentTo`. But what does `otherTangentTo` do if line is not in fact tangent to the conic?

Of course other names are possible, but `tangentTo` and `otherTangentTo` seem reasonable to me. If one were doing it from scratch, you then might want to call the current `tangent` by the name `tangentAt` to distinguish it, but I doubt you want to break backward compatibility for that sake.

**Comment by andreas-web** [comment]
I would suggest `tangentThrough` and a different order:
```
board.create('tangentThrough', [conic, point, i]);
```

From my point of view, it would also be conceivable to use the previous syntax:
```
board.create('tangentThrough', [pointOnConic, pointNotOnConic]);
```
Here you would not have the problem of having to choose between several. However, `pointOnConic` might have to be moved so that the solution can exist.

**Comment by gwhitney** [comment]
I'm fine with "tangentThrough" especially if the construction is creating a line rather than a segment, but I do think the ordinary English for what is happening here is "draw a tangent from point A to circle c". But either command name seems fine.
